// This file is generated by Prismic local builder. Update with care!

export { default as SectionProjects } from './SectionProjects'
export { default as SectionServices } from './SectionServices'
export { default as SectionSnap } from './SectionSnap'
export { default as SectionTestimonials } from './SectionTestimonials'
