import Head from 'next/head';
import SliceZone from 'next-slicezone';

import Client from '../utils/prismicHelpers';
import * as Slices from '../slices';
import Layout from '../components/layout';

export default function Home({ page, layout }) {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {page?.data && (
        <SliceZone slices={page.data.slices} resolver={({ sliceName }) => Slices[sliceName]} />
      )}
    </Layout>
  );
}

export async function getStaticProps() {
  const fetchLinks = `project.customer, project.title, project.extract, project.image, project.technologies, project.link`;
  const page = await Client().getByUID('page', 'home', { fetchLinks });
  const layout = (await Client().getByUID('layout', 'default', {})) || {};
  // console.log(layout);
  return {
    props: {
      page,
      layout,
    },
  };
}
