import Head from 'next/head';
import SliceZone from 'next-slicezone';

import Client from '../utils/prismicHelpers';
import * as Slices from '../slices';

export default function Home({ page }) {
  console.log(page);
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <p>Main</p>
      </main>

      {page?.data && (
        <SliceZone slices={page.data.slices} resolver={({ sliceName }) => Slices[sliceName]} />
      )}

      <footer className="">
        <p>Footer</p>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const page = await Client().getByUID('page', 'home');
  console.log(page);

  return {
    props: {
      page,
    },
  };
}
